### ISSUE TITLE
용어집 양식변경 - 대표어- 동의어  부분 추가

### ISSUE THREAD

**Issue by syohnet** [pythonkr/python-terms#3]
대표어 - 동의어를 추가하여 용어집 양식을 변경하면 어떨까요? 
예시.  
싸이킷런 sklearn 이지만 표기는 scikit-learn

|  **분류** | **용어 (대표어)** | **용어 (동의어)** | **발음** | **해설** | **비고** |
|  :------: | :------ | :------ | :------ | :------ | :------ |
|  라이브러리 | scikit-learn | sklearn | 싸이킷런 | 예제 샘플 생략 |

**Comment by amazingguni** [comment]
좋습니다 :smile_cat:

**Comment by amazingguni** [comment]
@ohahohah 
근데 문득 보다 보니까 용어집도 검색 가능한 형태면 더 편하지 않을까 싶은 생각도 드는데
어떻게 생각하세요~?

**Comment by syohnet** [comment]
오 그렇겠네요~ 지금 생각나는건 문자열 검색 + 등록하는 모듈을 만드는 건데 생각나시는 아이디어가 있으실까요? @amazingguni 
많은 분들이 참여하시기가 쉽고 말씀하신대로 검색 가능한 형태가 있으면 좋을 법 한데욥

**Comment by amazingguni** [comment]
@ohahohah
깃북을 쓰면 검색이 됩니다!
